# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: ontology2smw build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
#        exclude:
#          - os: windows-latest
#            python-version: 3.6
#          - os: windows-latest
#            python-version: 3.7
#          - os: windows-latest
#            python-version: 3.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -V
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pytest
#        pip install -r requirements.txt
    - name: install application
      run: |
        python setup.py install
    - name: test rdflib
      run: |
        python -c 'import rdflib.plugins.sparql'
    - name: run application
      run: |
        ontology2smw --format ttl --ontology https://raw.githubusercontent.com/tibonto/aeon/master/aeon.ttl
#    - name: Test with pytest
#      run: |
#        pytest